import Color from 'color';
import theme from '../@vex/utils/tailwindcss';

export const shippingTableLabels = [
  {
    text: 'New',
    backgroundColor: Color(theme.colors.green['500']).fade(0.9),
    color: theme.colors.green['500']
  },
  {
    text: 'Lead',
    backgroundColor: Color(theme.colors.cyan['500']).fade(0.9),
    color: theme.colors.cyan['500']
  },
  {
    text: 'In Progress',
    backgroundColor: Color(theme.colors.teal['500']).fade(0.9),
    color: theme.colors.teal['500']
  },
  {
    text: 'Completed',
    backgroundColor: Color(theme.colors.purple['500']).fade(0.9),
    color: theme.colors.purple['500']
  },
];

export const ShipingLocation = [
  {
    id: 0,
    bname : 'Kle',
    shipTo : 'Ubaid',
    address1 : 'Address1',
    address2 : 'Address2',
    city: 'Lahore',
    state: 'Punjab',
    country: 'Pakistan',
    postCode: '54000',
    loadPlan: 'load1',
    currency: 'currency2',
    ship2: 'ship2',
    contactPerson: 'dania2',
    shipBy:'sea',
    transhipment: 'Allowed',
    originOfGoods: 'malasia',
    type: 'type1',
    deliveryTerms: 'foPortKing2'

  },
  {
    id: 1,
    bname : 'Kle',
    shipTo : 'Madi',
    address1 : 'Address1',
    address2 : 'Address2',
    city: 'Lahore',
    state: 'Punjab',
    country: 'Pakistan',
    postCode: '54000',
    loadPlan: 'load1',
    currency: 'currency2',
    ship2: 'ship2',
    contactPerson: 'dania2',
    shipBy:'sea',
    transhipment: 'Allowed',
    originOfGoods: 'malasia',
    type: 'type1',
    deliveryTerms: 'foPortKing2'
   
  },
  {
    id: 2,
    bname : 'Kle',
    shipTo : 'Haroon',
    address1 : 'Address1',
    address2 : 'Address2',
    city: 'Lahore',
    state: 'Punjab',
    country: 'Pakistan',
    postCode: '54000',
    loadPlan: 'load1',
    currency: 'currency2',
    ship2: 'ship2',
    contactPerson: 'dania2',
    shipBy:'sea',
    transhipment: 'Allowed',
    originOfGoods: 'malasia',
    type: 'type1',
    deliveryTerms: 'foPortKing2'
  },
  {
    id: 3,
    bname : 'Kle',
    shipTo : 'Nauman',
    address1 : 'Address1',
    address2 : 'Address2',
    city: 'Lahore',
    state: 'Punjab',
    country: 'Pakistan',
    postCode: '54000',
    loadPlan: 'load1',
    currency: 'currency2',
    ship2: 'ship2',
    contactPerson: 'dania2',
    shipBy:'sea',
    transhipment: 'Allowed',
    originOfGoods: 'malasia',
    type: 'type1',
    deliveryTerms: 'foPortKing2'
  },
  {
    id: 4,
    bname : 'Kle',
    shipTo : 'Bakhtawar',
    address1 : 'Address1',
    address2 : 'Address2',
    city: 'Lahore',
    state: 'Punjab',
    country: 'Pakistan',
    postCode: '54000',
    loadPlan: 'load1',
    currency: 'currency2',
    ship2: 'ship2',
    contactPerson: 'dania2',
    shipBy:'sea',
    transhipment: 'Allowed',
    originOfGoods: 'malasia',
    type: 'type1',
    deliveryTerms: 'foPortKing2'
  },
  {
    id: 5,
    bname : 'Kle',
    shipTo : 'Khilada',
    address1 : 'Address1',
    address2 : 'Address2',
    city: 'Lahore',
    state: 'Punjab',
    country: 'Pakistan',
    postCode: '54000',
    loadPlan: 'load1',
    currency: 'currency2',
    ship2: 'ship2',
    contactPerson: 'dania2',
    shipBy:'sea',
    transhipment: 'Allowed',
    originOfGoods: 'malasia',
    type: 'type1',
    deliveryTerms: 'foPortKing2'
  },
  {
    id: 6,
    bname : 'Kle',
    shipTo : 'Amana',
    address1 : 'Address1',
    address2 : 'Address2',
    city: 'Lahore',
    state: 'Punjab',
    country: 'Pakistan',
    postCode: '54000',
    loadPlan: 'load1',
    currency: 'currency2',
    ship2: 'ship2',
    contactPerson: 'dania2',
    shipBy:'sea',
    transhipment: 'Allowed',
    originOfGoods: 'malasia',
    type: 'type1',
    deliveryTerms: 'foPortKing2'
  },
  
];
